apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - flyway-creds.yaml

namespace: prod

helmCharts:
  - name: postgresql
    version: 18.8.4
    releaseName: postgresql
    repo: https://charts.bitnami.com/bitnami
    valuesFile: postgres-values.yaml
  - name: pgadmin4
    version: 1.65.0
    releaseName: pgadmin
    repo: https://helm.runix.net
    valuesFile: pg-admin-values.yaml