env:
  email: "admin@example.com"
  password: "SuperSecurePgAdminPassword123"

# Automatically pre-configure the PostgreSQL connection inside pgAdmin
serverDefinitions:
  enabled: true
  servers:
    1:
      Name: "Kubernetes Postgres"
      Group: "Servers"
      Host: "postgres-postgresql.prod.svc.cluster.local"
      Port: 5432
      MaintenanceDB: "postgres"
      Username: "postgres"
      SSLMode: "prefer"

# Ingress Configuration
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: pgadmin.minikube.local
      paths:
        - path: /
          pathType: Prefix

persistentVolume:
  enabled: true
  size: 2Gi