{{- if eq .Values.kind "Deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.image.repository }}-deploy
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.image.repository }}-deploy
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.image.repository }}-deploy
  template:
    metadata:
      labels:
        app: {{ .Values.image.repository }}-deploy
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: {{ .Values.image.repository }}
          image: "{{ .Values.image.registry}}{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: {{ .Values.port }}
              protocol: TCP
          env:
            - name: DATABASE_CONNECTION_STRING
              value: "postgresql+asyncpg://appuser:AppUserPassword123@postgresql.prod.svc.cluster.local:5432/prod"
            - name: RABBIT_CONNECTION_STRING
              value: "amqp://user:password@rabbitmq.prod.svc.cluster.local:5672/"
          # envFrom:
          #   - secretRef:
          #       name: boa-env
{{- end }}