{{- if eq .Values.kind "Job" }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.image.repository }}-job
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    app: {{ .Values.image.repository }}-job
spec:
  backoffLimit: {{ .Values.job.backoffLimit }}
  template:
    metadata:
      labels:
        app: {{ .Values.image.repository }}-job
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      restartPolicy: {{ .Values.job.restartPolicy }}
      containers:
        - name: {{ .Values.image.repository }}
          image: "{{ .Values.image.registry}}{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          envFrom:
            - secretRef:
                name: flyway-creds
          {{- if .Values.job.command }}
          command:
            {{- toYaml .Values.job.command | nindent 12 }}
          {{- end }}
          {{- if .Values.job.args }}
          args:
            {{- toYaml .Values.job.args | nindent 12 }}
          {{- end }}
{{- end }}