{{- if and (eq .Values.kind "Deployment") .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.image.repository }}-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.image.repository }}-svc
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.image.repository }}-deploy
{{- end }}