controller:
  admin:
    username: admin
    password: mySuperSecretPassword 

  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "2000m"
      memory: "4Gi"

  ingress:
    enabled: true
    ingressClassName: nginx
    hostName: jenkins.minikube.local
    paths: []


  additionalExistingSecrets:
    - name: jenkins-github-token
      keyName: token

  JCasC:
    defaultConfig: true

    configScripts:
      custom-config: |
        appearance:
          prism:
            theme: PRISM

        security:
          gitHostKeyVerificationConfiguration:
            sshHostKeyVerificationStrategy: "knownHostsFileVerificationStrategy"

        unclassified:
          globalLibraries:
            libraries:
              - name: "jenkins-shared-library"
                defaultVersion: "main"
                retriever:
                  modernSCM:
                    libraryPath: "."
                    scm:
                      gitSource:
                        remote: "https://github.com/adrian-hawkins-portfolio/adoption_agency.k8s.jenkins.git"
                        traits:
                          - "gitBranchDiscovery"

        credentials:
          system:
            domainCredentials:
              - credentials:
                  - usernamePassword:
                      id: "github-push-token"
                      scope: GLOBAL
                      username: "Adrian-Hawkins"
                      password: "${jenkins-github-token-token}"

agent:
  podTemplates:
    docker-agent: |
      - name: docker-agent
        label: docker-agent
        yamlMergeStrategy: "override"
        yaml: |-
          apiVersion: v1
          kind: Pod
          spec:
            serviceAccountName: jenkins-helm-agent
            imagePullSecrets:
              - name: ghcr-secret
            containers:
              - name: jnlp
                image: ghcr.io/adrian-hawkins-portfolio/docker-agent:4.0
                securityContext:
                  privileged: true
                  runAsUser: 0
                volumeMounts:
                  - name: docker-sock
                    mountPath: /var/run/docker.sock
                  - name: ghcr-docker-config
                    mountPath: /home/jenkins/.docker/config.json
                    subPath: .dockerconfigjson
                    readOnly: true
                envFrom:
                  - secretRef:
                      name: pypi-info
                env:
                  - name: DOCKER_CONFIG
                    value: /home/jenkins/.docker
            volumes:
              - name: docker-sock
                hostPath:
                  path: /var/run/docker.sock
                  type: Socket
              - name: ghcr-docker-config
                secret:
                  secretName: ghcr-secret
                  items:
                    - key: .dockerconfigjson
                      path: .dockerconfigjson