apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

helmCharts:
  - name: minio
    repo: https://charts.min.io/
    releaseName: minio
    valuesFile: minio-values.yaml
    includeCRDs: true