mode: standalone

rootUser: "admin"
rootPassword: "password123"

persistence:
  enabled: true
  size: 5Gi

# 1. Ingress for the Web Console UI
consoleIngress:
  enabled: false   # Gateway API takes over routing instead

ingress:
  enabled: false   # same here