apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace: jenkins

helmCharts:
  - name: rabbitmq
    version: 15.0.0
    repo: https://charts.bitnami.com/bitnami
    releaseName: rabbitmq
    valuesFile: rabbit-values.yaml