apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace: jenkins
resources:
  - secret-tls.yaml
  - envoy-gw-class.yaml
  - envoy-gw.yaml
  - jenkins-http-route.yaml
  - pg-tcp-route.yaml
  - grafana-prom-http-route.yaml
  - pg-admin-http-route.yaml
  - rabbitmq-http-route.yaml
