# Set to "Deployment" or "Job"
kind: Deployment

image:
  repository: nginx
  registry: ghcr.io/adrian-hawkins-portfolio/
  tag: "latest"

port: 8080

# ---------------------------------------------------------
# Deployment Specific Configuration
# ---------------------------------------------------------
replicaCount: 1

# Service (Only created if kind == Deployment AND enabled == true)
service:
  enabled: false

# # Ingress (Only created if kind == Deployment AND enabled == true)
ingress:
  enabled: false

# HPA (Only created if kind == Deployment AND enabled == true)
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

# ---------------------------------------------------------
# Job Specific Configuration
# ---------------------------------------------------------
job:
  backoffLimit: 4
  restartPolicy: Never
  command: []
  args: []