base:
  kind: Job

  image:
    repository: pet-database
    tag: "v1.2.0"

  job:
    backoffLimit: 3
    # restartPolicy: OnFailure
    command: ["/bin/sh", "-c"]
    args: ["python process_batch.py"]