apiVersion: v1
kind: Pod
spec:
  serviceAccountName: jenkins-helm-agent
  imagePullSecrets:
    - name: ghcr-secret
  containers:
    - name: jnlp
      image: ghcr.io/adrian-hawkins-portfolio/docker-agent:4.0
      securityContext:
        privileged: true
        runAsUser: 0
      volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock
        - name: ghcr-docker-config
          mountPath: /home/jenkins/.docker/config.json
          subPath: .dockerconfigjson
          readOnly: true
      envFrom:
        - secretRef:
            name: pypi-info
      env:
        - name: DOCKER_CONFIG
          value: /home/jenkins/.docker
  volumes:
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock
        type: Socket
    - name: ghcr-docker-config
      secret:
        secretName: ghcr-secret
        items:
          - key: .dockerconfigjson
            path: .dockerconfigjson